name: generative_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_file_dialog: ^3.0.2
  get: ^4.6.6
  image: ^4.3.0
  image_picker: ^1.0.8
  path_provider: ^2.1.4
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
